---
title: ''
author: ''
csl: aje_style.csl
output:
  pdf_document: default
  html_document:
    df_print: paged
header-includes:
- \usepackage[T1]{fontenc}
- \usepackage{microtype}
- \usepackage[margin=1in]{geometry}
- \usepackage{fancyhdr}
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhead{}
- \fancyfoot{}
- \fancyhead[C]{Animal Help Now}
- \fancyfoot[RO,LE]{\thepage}
- \usepackage{booktabs}
- \usepackage{lettrine}
- \usepackage{paralist}
- \usepackage{setspace}\singlespacing
- \usepackage{url}
- \usepackage{parskip}
- \usepackage{color,soul}
- \usepackage{palatino}
- \usepackage{float}
- \usepackage{amsmath}
bibliography: refs_fake.bib
---

\doublespacing

\begin{center}
\textbf{ \LARGE{Project Log: Animal Help Now} }
\vspace{10mm}
\end{center}

\doublespacing


\tableofcontents

Shiny/GA app tutorial: https://www.youtube.com/watch?v=4Ht_vEXJ4wo&feature=youtu.be

The field "Action Taken from Helper Details" seems very useful since this seems to correspond to whether the subject actually clicked to call/email/visit the website of the helper.  

\section{Open questions}

\begin{enumerate}
\item How do I get a full enumeration of the custom variables in GA? Like "HelperDetail_Displayed"?
\end{enumerate}


\section{Resolved questions}

\subsection{How do I get reproduce the Dashboard?}

Go to the "Report Configuration" tab. Query the same metric and dimensions as are listed there. Note that for Android, it's eventAction instead of eventCategory, and using the latter results in too few sessions.  

\newpage
\section*{References}


